[build]
  command = "npm run build -- --no-lint"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/stream/*"
  to = "http://aczv.asia/live/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/rtc/*"
  to = "http://aczv.asia/rtc/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
